#!/usr/bin/env python3

import argparse
import os
import re


def randomize_env_file(base_path):
    local_file_name = os.path.join(base_path, ".env")
    public_file_name = os.path.join(base_path, ".env.pub")

    # Check if .env.local exists
    if not os.path.exists(local_file_name):
        print(f"{local_file_name} file not found!")
        return

    with open(local_file_name, "r") as source:
        lines = source.readlines()

    env_vars = []
    current_default = None
    should_ignore = False

    with open(public_file_name, "w") as target:
        for i, line in enumerate(lines):
            line = line.strip()

            # Check if this line should be ignored
            if line.startswith("# IGNORE"):
                should_ignore = True
                # Don't write IGNORE comment to .env.pub
                continue

            # Check if this line specifies a default value
            if line.startswith("# DEFAULT:"):
                current_default = line[len("# DEFAULT:") :].strip()
                target.write(line + "\n")
                continue

            # Write empty lines and regular comments as is
            if not line or (line.startswith("#") and not line.startswith("# DEFAULT:")):
                target.write(line + "\n")
                current_default = (
                    None  # Reset default if we encounter any other comment
                )
                continue

            # Split the line into key and value
            if "=" in line:
                key, original_value = line.split("=", 1)
                key = key.strip()
                original_value = original_value.strip()

                # Skip this variable if it should be ignored
                if should_ignore:
                    should_ignore = False  # Reset for next variable
                    current_default = None
                    continue

                env_vars.append(key)

                # Use default value if one was specified in the preceding comment
                if current_default is not None:
                    new_value = current_default
                    # Apply appropriate formatting (quotes) if needed
                    if original_value.startswith('"') or original_value.startswith("'"):
                        quote = original_value[0]
                        if not (
                            new_value.startswith(quote) and new_value.endswith(quote)
                        ):
                            new_value = f"{quote}{new_value}{quote}"
                else:
                    # Generate random value based on original value pattern
                    if original_value.startswith('"') or original_value.startswith("'"):
                        # String value
                        quote = original_value[0]
                        new_value = f"{quote}xxxx{quote}"
                    elif original_value.isdigit():
                        # Numeric value
                        new_value = 1234
                    else:
                        # Default to random string
                        new_value = "xxxx"

                # Write the new line
                target.write(f"{key}={new_value}\n")
                current_default = None  # Reset default after using it
            else:
                # If line doesn't contain '=', write it as is
                target.write(line + "\n")
                current_default = None  # Reset default if no key-value pair follows
                should_ignore = False  # Reset ignore flag

    # Update Dockerfile with ARG statements
    dockerfile_found = update_dockerfile(env_vars, base_path)
    print(
        f"Successfully created .env.pub with randomized values{' and updated Dockerfile!' if dockerfile_found else '!'}"
    )


def update_dockerfile(env_vars, base_path):
    dockerfile_path = os.path.join(base_path, "Dockerfile")

    # Read the Dockerfile
    # Check if Dockerfile exists
    if not os.path.exists(dockerfile_path):
        return False
    with open(dockerfile_path, "r") as file:
        content = file.read()

    # Create ARG statements
    arg_statements = "\n".join([f"ARG {var}" for var in env_vars])
    arg_statements += "\n"

    # Replace the section between markers
    pattern = r"### Start autogenerated \(update_env\.py\).*?### End autogenerated"
    replacement = f"### Start autogenerated (update_env.py)\n{arg_statements}### End autogenerated"
    new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

    # Write the updated Dockerfile
    with open(dockerfile_path, "w") as file:
        file.write(new_content)

    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate .env.pub file with randomized values"
    )
    parser.add_argument("base_path", help="Base path where .env file is located")

    args = parser.parse_args()

    randomize_env_file(args.base_path)
